version: '3'
services:
  il-padrino-della-famiglia:
    build:
      context: ./Godfather_Discord_Bot
      dockerfile: Dockerfile
    container_name: Godfather_Discord_Bot
    restart: unless-stopped
    environment:
      - discord_token=TOKEN_BOT
      - discord_server_name=Famiglia Old School
    volumes:
      - ./Godfather_Discord_Bot:/app
  devart-support:
    build:
      context: ./DevArt_Support_Discord_Bot
      dockerfile: Dockerfile
    container_name: DevArt_Support_Discord_Bot
    restart: unless-stopped
    environment:
      - discord_token=TOKEN_BOT
    volumes:
      - ./DevArt_Support_Discord_Bot:/app